name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v4
      - uses: snakemake/snakemake-github-action@v2
        with:
          directory: "."
          snakefile: workflow/Snakefile
          args: "--cores 1 --sdm conda -n"
          stagein: '' # additional preliminary commands to run (can be multiline)
          show-disk-usage-on-error: true